# Monitoring - Prometheus, kube-state-metrics, Grafana
# =====================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - kube-state-metrics.yaml
  - grafana-configmap-datasource.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-alerting-configmap.yaml
  - grafana-admin-sealed.yaml
  - grafana-discord-webhook-sealed.yaml
  - grafana-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: kubesecurebox
  app.kubernetes.io/component: monitoring
