# ArgoCD Apps Kustomization
# =========================
# Regroupe toutes les applications ArgoCD
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure.yaml
  - apps.yaml
