# RBAC : Ingress NGINX doit pouvoir lire le Secret TLS dans le namespace website
# ================================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-nginx-tls-reader
  namespace: website
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx-tls-reader
  namespace: website
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
roleRef:
  kind: Role
  name: ingress-nginx-tls-reader
  apiGroup: rbac.authorization.k8s.io
